### ISSUE TITLE
Add Ollama integration

### ISSUE THREAD

**Issue by vishalkrv** [deepseek-ai/Janus#11]
Can we get this on ollama, please ?

**Comment by charlesCXK** [comment]
Sorry for the late reply. We've been occupied with internal projects and haven't had time to migrate the model to Ollama yet. 😔

**Comment by limingchina** [comment]
Is there still plan to support that?

**Comment by ozbillwang** [comment]
could we re-open this request?

**Comment by agaldemas** [comment]
Yep, I am also looking for a working janus model version for ollama ;O), the only one found is ozbillwang/deepseek-janus-pro, which give this error on my Mac M3: 
```
ollama run ozbillwang/deepseek-janus-pro
pulling manifest 
pulling a338945d54b9... 100% ▕██████████████████████████████████████▏ 4.6 MB                         
pulling f0fd86e87432... 100% ▕██████████████████████████████████████▏  353 B                         
verifying sha256 digest 
writing manifest 
success 
Error: llama runner process has terminated: error loading model: missing tensor 'token_embd.weight
```
....so re-open this issue !

**Comment by ozbillwang** [comment]
> Yep, I am also looking for a working janus model version for ollama ;O), the only one found is ozbillwang/deepseek-janus-pro, which give this error on my Mac M3:

Please check if this works for you.

https://ollama.com/gguf/DeepSeek-Janus-Pro-7B

![Image](https://github.com/user-attachments/assets/88dd0fc5-6928-4710-9ae6-13aba3196c7d)

**Comment by mTxBeN** [comment]
Yes would love to see an ollama version of Janus Pro 7B please to run on local. Thanks 😊

**Comment by ozbillwang** [comment]
> Yes would love to see an ollama version of Janus Pro 7B please to run on local. Thanks 😊

check this  https://ollama.com/gguf/DeepSeek-Janus-Pro-7B

```
ollama run gguf/DeepSeek-Janus-Pro-7B
```

If compare to SD, Janus is loser. SD is faster.

**Comment by agaldemas** [comment]
Thanks, @ozbillwang, I maanged to load it and run (ollama run gguf/DeepSeek-Janus-Pro-7B) !
Nice but which UI tool can we use to generate images  ?

Some links are welcome
