### ISSUE TITLE
Multiple Images per a message?

### ISSUE THREAD

**Issue by DenisSergeevitch** [deepseek-ai/Janus#13]
Hello, and thank you for sharing such a novel model.

I have checked the inference code, and it looks like it's working only with a single image per message. Attaching more causes a Tensor mismatch.

Does the model not support multiple images per user message?

**Comment by charlesCXK** [comment]
Sorry for the late reply. Our model has been trained on multi-image QA data, but we only provided a single-image version when writing the demo code.
