### ISSUE TITLE
Config.json Error

### ISSUE THREAD

**Issue by AKjhu** [deepseek-ai/Janus#20]
Hello, 

I am currently facing an issue where I cannot use the model, as the model_type field in the config.json is "multi_modality". Transformers then throws a ValueError, stating that Transformers does not recognize that architecture. I have tried uninstalling and reinstalling Transformers again before running as well as installing from source rather than pip, but nothing has seemed to work. I was wondering if there is a change or different model_type that should be used here?

**Comment by charlesCXK** [comment]
Sorry for the late reply. It sounds like an issue with the runtime environment. You can set up the environment using the commands provided in the README.
