### ISSUE TITLE
Can not reproduce the t2i result on MSCOCO-30K

### ISSUE THREAD

**Issue by Junction4Nako** [deepseek-ai/Janus#22]
Thanks for the awesome work!

I am trying to reproduce the text-to-image generation results on MSCOCO-30K.

I utilize the function in [simple inference example](https://github.com/deepseek-ai/Janus#simple-inference-example) for generation without the default parameters (I set the parallel_size to 1 for evaluation).

For the sampled 30K queries and evaluation methods, I utilize the tool provided in https://github.com/boomb0om/text2image-benchmark/tree/main.

Here are other system infos:
torchversion: 2.5.0
cuda: 12.3
GPU: NVIDIA A100-PG509-40G
transformers version: 4.46.0
Python version: 3.9.20

The obtained FID results is around 16, which is not same as the reported 8.53. I perform a sanity check by using the query in the online demo and find the generated image is similar to the one generated by the online demo.

Could you please provide the setting or scripts for the corresponding evaluation results?

**Comment by charlesCXK** [comment]
We use this [script](https://github.com/mingukkang/GigaGAN/blob/main/evaluation/evaluation.py) for evaluating FID. The 30k images are randomly selected from COCO val 2014. The eval resolution is 256 ('bicubic' downsampled from the original 384 output image).

**Comment by Junction4Nako** [comment]
Thank you for the clarification. I have reproduced the results, the reason for the previous misalignment is due to that I used inception_v3 as the extractor.

**Comment by Huiimin5** [comment]
> Thank you for the clarification. I have reproduced the results, the reason for the previous misalignment is due to that I used inception_v3 as the extractor.

Do you mean that the feature extractor should be set to "clip" in order to obtain FID 8.53?

**Comment by david-jx-second** [comment]
> Thanks for the awesome work!
> 
> I am trying to reproduce the text-to-image generation results on MSCOCO-30K.
> 
> I utilize the function in [simple inference example](https://github.com/deepseek-ai/Janus#simple-inference-example) for generation without the default parameters (I set the parallel_size to 1 for evaluation).
> 
> For the sampled 30K queries and evaluation methods, I utilize the tool provided in https://github.com/boomb0om/text2image-benchmark/tree/main.
> 
> Here are other system infos: torchversion: 2.5.0 cuda: 12.3 GPU: NVIDIA A100-PG509-40G transformers version: 4.46.0 Python version: 3.9.20
> 
> The obtained FID results is around 16, which is not same as the reported 8.53. I perform a sanity check by using the query in the online demo and find the generated image is similar to the one generated by the online demo.
> 
> Could you please provide the setting or scripts for the corresponding evaluation results?

Did you try to reproduce `GenEval`? I used the settings in `generation_inference.py` but got lower results with much difference. 
If you have reproduced it, could you please share your settings? 
I would greatly appreciate your help！
