### ISSUE TITLE
Mac(M1/M2/M3) mlx support?

### ISSUE THREAD

**Issue by arunbaby0** [deepseek-ai/Janus#9]
Can this model be used in macbook m1/m2/m3? 
Is there any mlx support?

**Comment by fivehanz** [comment]
same question, +1

**Comment by gradetwo** [comment]
[mlx.patch](https://github.com/user-attachments/files/17729098/mlx.patch)
use this patch

**Comment by chunchung223** [comment]
for Mac 
1. pip install -e .
2. pip install gradio
3. pip uninstall torch torchvision torchaudio -y
4. conda install pytorch::pytorch torchvision torchaudio -c pytorch
5. python demo/app_januspro.py
6. http://127.0.0.1:7860
